### ISSUE TITLE
RecordNotFound error from LiveQuery after removing record

### ISSUE THREAD

**Issue by simonihmig** [orbitjs/ember-orbit#179] opened 2019-04-15 19:02 UTC
Not sure who is to blame here, `ember-orbit` (using master branch) or `orbit.js`(0.16.0-beta.4), so putting this here first.

After removing a record, I am getting a `RecordNotFound` error, visible in the console, for *this very* record.

I don't have a reproduction repo, but hopefully this sequence of screenshots is able to illustrate the problem sufficiently:

The last stack trace item originating in our app itself does this:
```
return this.store.removeRecord({
  type: 'assumptionTree',
  id: tree.id
});
```

Much higher up in the stack trace, after the API source has successfully(!) deleted the record, ember-orbit`s LiveQuery, which handles a hasMany relationship for that deleted record, gets notified here:

![image](https://user-images.githubusercontent.com/1325249/56157705-7a327f00-5fc0-11e9-9e4e-aa98f2836e06.png)

This kicks off property change notifications on the ArrayProxy, here for `arrangedContent`:

![image](https://user-images.githubusercontent.com/1325249/56157824-cc73a000-5fc0-11e9-8b68-12ecd2b20847.png)

Which higher up the stack trace triggers a reevaluation of LiveQuery's `content` getter, which in turn calls into Orbit (`record` here is the deleted record!):

![image](https://user-images.githubusercontent.com/1325249/56157953-0fce0e80-5fc1-11e9-859f-a1e9d35fc746.png)

This finally throws in Orbit's (new) RecordCache:

![image](https://user-images.githubusercontent.com/1325249/56158026-3c822600-5fc1-11e9-91f1-a01c0a75f95d.png)

I guess as the error is thrown in RecordCache, this is the code that has recently changed AFAIK, and is probably causing this changed behavior. But as I said not sure who is to be blamed here, maybe this should be catched and prevented in ember-orbit?

**Comment by simonihmig** [comment] 2019-04-18 07:35
@dgeb did you have a chance to look at this? 

Sorry for my impatience, but this is currently blocking us form upgrading. And happy to help with a PR if I can, just need to better understand how a solution should look like!

**Comment by tchak** [comment] 2019-05-10 08:05
I think this happens because the `patch` watcher on the `LiveQueryArray` is way too agressive. I will look in to it.

**Comment by dgeb** [comment] 2019-05-10 08:55
@simonihmig Sorry to delay with a reply. I'm debugging this with @tchak in person now. It seems that we need to expand [Model#disconnect](https://github.com/orbitjs/ember-orbit/blob/master/addon/-private/model.js#L77-L79) to also disconnect any relationship live queries.

**Comment by simonihmig** [comment] 2019-05-15 15:06
>  I'm debugging this with @tchak in person now.

Sorry to bug you guys again, but has this been somehow successful?

**Comment by dgeb** [comment] 2019-05-15 17:23
@simonihmig yes, we identified the problem but got distracted before shipping a fix. Sorry for the delay - I'll get a fix out by tomorrow at the latest.

**Comment by dgeb** [comment] 2019-05-17 21:07
I have not forgotten this, but I had to merge a large PR as well as some test upgrades before getting to it. I'm working on a reproduction in the tests and a fix now ...

**Comment by dgeb** [comment] 2019-05-17 22:21
@simonihmig please try `master` - this should be fixed via #185.

**Closed** 2019-05-17 22:20 UTC

**Comment by simonihmig** [comment] 2019-05-17 23:01
@dgeb Fantastic, thank you! 

I quickly tried to update it my project, but this failed due to the `ember-orbit:config` changes. The app uses MU, so this probably needs some fixes to our custom setup. Will try this again on Monday hopefully, and post my feedback asap!

**Comment by simonihmig** [comment] 2019-05-21 18:12
So, I was now able to update our app to latest ember-orbit (master) and orbit (0.16-beta.x) and this indeed fixed the last remaining issue. All tests are green again :tada:

Thanks @dgeb & @tchak!

**Comment by dgeb** [comment] 2019-05-21 18:57
@simonihmig great! Glad you can finally update to the beta (and start using hints and the other new features) 😄
